name: Android Build & Release
on:
    push:
        branches:
            main
env:
    java_version: 17

jobs:
    build-dev-android:
        runs-on: ubuntu-latest
        environment: development
        steps:

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setting up node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Setup java JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'zulu'
            - run: |
                echo "Java JDK 17 Set up Successfully"

            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v3

            - name: Install Dependencies
              run: |
                yarn
                echo "Project Dependencies are installed"
            
            - name: Create Staging Env
              run: |
                echo "API_URL=${{ vars.API_URL }}" > .env
                echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
                echo ".env file created successfully!"

            - name: Android Release Build
              run: |
                cd android && ./gradlew assembleRelease

            - name: Upload Release Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: android-dev-artifact
                path: ./android/app/build/outputs/apk/release/app-release.apk
                retention-day: 7
            - name: Environments
              run: |
                echo "API URL = ${{ vars.API_URL }}"

    build-stage-android:
        runs-on: ubuntu-latest
        environment: staging
        steps:

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setting up node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Setup java JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'zulu'
            - run: |
                echo "Java JDK 17 Set up Successfully"

            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v3

            - name: Install Dependencies
              run: |
                yarn
                echo "Project Dependencies are installed"
            
            - name: Create Staging Env
              run: |
               echo "API_URL=${{ vars.API_URL }}" > .env
               echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
               echo ".env file created successfully!"

            - name: Android Release Build
              run: |
                cd android && ./gradlew assembleRelease

            - name: Upload Release Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: android-stage-artifact
                path: ./android/app/build/outputs/apk/release/app-release.apk
                retention-day: 7

            - name: Environments
              run: |
                echo "API URL = ${{ vars.API_URL }}"





    